### PR TITLE
Hotfix-proposed data

### LINKED ISSUE #910: While running 2 nodes, give sorted is getting called.
#### System information

- **OS & Version**: Ubuntu
- **Go version:** go 1.17
- **razor-go version:** mainnet-stable

#### Describe the bug
When running 2 nodes, give sorted is getting called, because razor-go tries to fetch the last epoch's value and not this epoch's value.

#### Steps to reproduce the behaviour
1. Run 2 nodes
2. Check if values of last proposed epoch are correct.

### PR DESCRIPTION
**Pull request by Yashk767**
# Description

- Updated proposed data global variables correctly.
- We save the propose data to proposedDataFile only on successful propose.

Fixes #910

### CODE REVIEW

File: cmd/dispute.go [hunk 1]
```diff
@@ -224,14 +221,17 @@ CalculateMedian:
...
+			RevealedDataMaps:      revealedDataMaps,
+			Epoch:                 epoch,
+		})
 	}
 
 	log.Debug("Locally calculated data:")
-	log.Debugf("Medians: %d", _mediansData)
-	return _mediansData, _revealedCollectionIds, _revealedDataMaps, nil
+	log.Debugf("Medians: %d", globalProposedDataStruct.MediansData)
+	return globalProposedDataStruct.MediansData, globalProposedDataStruct.RevealedCollectionIds, globalProposedDataStruct.RevealedDataMaps, nil
```
Comment (ashish10677) [inline cmd/dispute.go:234]: You can return globalProposedDataStruct directly right?

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: cmd/dispute.go (hunk 1 above)
Comment (Yashk767) [reply cmd/dispute.go:234]: globalProposedDataStruct has extra field `epoch`.
Should we return `epoch` as well from `GetLocalMediansData` ?

**Review by ashish10677 — APPROVED** [review]
