### PR TITLE
Hotfix-giveSorted

### LINKED ISSUE #911: giveSorted fixes
#### Describe the bug
Once givesorted tx is confirmed, the next givesorted should know where it has to start from. 

#### Expected behaviour

- [x] if there is no need of givesorted it should not call it.

- [x] if prev giveSorted was incorrect, then reset dispute and start again.

- [ ] if prev giveSorted was correct, do not call giveSorted again. even if finalize dispute fails.

https://razorscan.io/tx/0xb962064a6f3d3a76852dc0e9c94f1943e015908e0e76628e4ea4053dde551575

https://razorscan.io/tx/0x2cade48c0cc69e7180b17bf870a68fee827243e4937933c534bc6440578c5f05

- [x] if one of the givesorted fails, then reset and try again (in recursion)
- [x] If govesorted fails, do not call finalizeDispute

#### Steps to reproduce the behaviour

Run 2 nodes, the other node tries to give Sorted.

- [x] Scenario 1: giveSorted goes thru in 1 go
- [x] Scenario 2: giveSorted exceeds gas limit, is split into multiple calls and executed sequentially
- [x] Scenario 3: giveSorted exceeds gas limit, but one of the calls fails.
//	eg: chunks of 10, among 100. Here if first chunk fails, then second onwards should not be called. This does not happen.

- [x] Scenario 4: redundant nodes run giveSorted. 
// a. giveSorted chunk is called by first node a and succeeds.
// b. node b is not aware of this, and calls giveSorted for the same chunk, and the transaction fails.
// c. node b thinks it is an invalid giveSorted, and calls resetDispute.
// d. node a is not able to finalise dispute because it was reset by node b. 

- [x] Scenario 5: node is restarted in dispute state.
// Currenlty, giveSorted is called again for all. If giveSorted is called previously, then resetDispute is called.

- [x]  Scenario 6: node a does giveSorted but tx is pending
// if tx is not confirmed, node b also does giveSorted
// node b's tx fails. node a's tx is successful.
// Since we are validating giveSorted from the blockchain, node b will not call ResetDispute.

- [x] Scenario 7: onchain state is invalid and both nodes call resetDispute at the same time.
// node a: resetDispute (n: 1), giveSorted (n: 2)
// node b: resetDispute (n: 2), giveSorted (n: 3)

- [ ]  Scenario 8: node a givesSorted for block 1, node b does the same for block 7
// node should check on chain state and should not continue dispute for block 7 when block on is ongoing. It should continue dispute for block 1.
// node b will end up never disputing for block 7. we should recheck for disputes multiple times in the state.

// Solution:
- [x]  1. calculate nonce from confirmed transactions and not pending transactions
- [x]  2. Validate disputes status before every dispute-related call.-

The index of the smallest sorted values should be greater to your LVV.

- [] a. node should be aware of dispute status. If the block is already disputed, then we should not go thru with dispute.
- [x]  b. node should be aware of ongoing dispute, and continue it.
- [x]  3. Repeat dispute calculation off chain multiple times throughout dispute state.

fetch from disputes struct: https://github.com/razor-network/oracle-contracts/blob/master/contracts/Core/storage/BlockStorage.sol#L7

### PR DESCRIPTION
**Pull request by Yashk767**
# Description

- Reset Dispute is only after `FinalizeDispute`, removed from other dispute types.
- `ResetDispute` called irrespective of `FinalizeDispute` Txn status.

Fixes #911

### CODE REVIEW

File: cmd/dispute.go [hunk 1]
```diff
@@ -304,59 +289,83 @@ func (*UtilsStruct) CheckDisputeForIds(client *ethclient.Client, transactionOpts
...
+			err = cmdUtils.StoreBountyId(client, account)
+			if err != nil {
+				return err
+			}
+		} else {
+			log.Error("Error in WaitForBlockCompletion for FinalizeDispute: ", WaitForBlockCompletionErr)
 		}
 	}
+
+	//Resetting dispute irrespective of FinalizeDispute transaction status
```
Comment (ashish10677) [inline cmd/dispute.go:337]: Are you sure we have to reset dispute irrespective of whether FinalizeDispute goes through or not?

File: cmd/dispute.go [hunk 2]
```diff
@@ -304,59 +289,83 @@ func (*UtilsStruct) CheckDisputeForIds(client *ethclient.Client, transactionOpts
...
 	if err != nil {
+		log.Error("Error in calling GiveSorted: ", err)
 		if err.Error() == errors.New("gas limit reached").Error() {
-			log.Error("Error in calling GiveSorted: ", err)
 			mid := len(sortedValues) / 2
-			GiveSorted(client, blockManager, txnOpts, epoch, leafId, sortedValues[:mid])
-			GiveSorted(client, blockManager, txnOpts, epoch, leafId, sortedValues[mid:])
+			err1 := GiveSorted(client, blockManager, txnOpts, epoch, leafId, sortedValues[:mid])
+			err2 := GiveSorted(client, blockManager, txnOpts, epoch, leafId, sortedValues[mid:])
+			if (err1 == nil && err2 != nil) || (err1 != nil && err2 == nil) {
```
Comment (ashish10677) [inline cmd/dispute.go:364]: Shouldn't this be `if err1 != nil || err2 != nil`?
Even if we get one error, that means that we have to reset dispute right?

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: cmd/dispute.go (hunk 1 above)
Comment (Yashk767) [reply cmd/dispute.go:337]: Hmm yes, discussed with @SamAg19. 

After giveSorted, the state of dispute changes so irrespective of FinalizeDispute txn status, we need to reset the state for the next dispute. So that next giveSorted for other proposed block goes through.

File: cmd/dispute.go (hunk 2 above)
Comment (Yashk767) [reply cmd/dispute.go:364]: But if we get error in both i.e. `err1 != nil` &&` err2 != nil `, we dont need to reset dispute.

**Review by ashish10677 — APPROVED** [review]

**Review by shekhar2807 — APPROVED** [review]
