### PR TITLE
Test Fix

### LINKED ISSUE #627: Fix tests of razor-go

### PR DESCRIPTION
**Pull request by shekhar2807**
# Description

- The current tests are fix for most of the files.
- Some tests are commented as they are related to new functions which are introduced.
   - Ex. In vote_test.go new function created in utils "CalculateBlockNumberAtEpochBeginning" .
   - In increasing the coverage PR this will be solved after covering the above function.  

Fixes #627

### CODE REVIEW

File: utils/asset_test.go [hunk 1]
```diff
@@ -475,10 +475,10 @@ func TestGetAllCollections(t *testing.T) {
...
 
 	type args struct {
-		numAssets     uint16
-		numAssetsErr  error
-		assetType     uint8
-		assetTypeErr  error
+		numAssets    uint16
+		numAssetsErr error
+		assetType    uint8
+		//assetTypeErr  error
```
Comment (ashish10677) [inline utils/asset_test.go:481]: Remove this if not required

Comment (shekhar2807) [reply utils/asset_test.go:481]: Tests for this will be added in increase coverage PR . So I commented it out and will be covered in other PR.

File: utils/asset_test.go [hunk 2]
```diff
@@ -814,10 +814,10 @@ func TestGetJobs(t *testing.T) {
...
 
 	type args struct {
-		numJobs      uint16
-		numJobsErr   error
-		assetType    uint8
-		assetTypeErr error
+		numJobs    uint16
+		numJobsErr error
+		assetType  uint8
+		//assetTypeErr error
```
[the remark this answers is not in the document]
Comment (shekhar2807) [reply utils/asset_test.go:820]: Same as above.

**Review by ashish10677 — APPROVED** [review]
