### PR TITLE
Dispute influence id fix

### LINKED ISSUE #331: Blocks with wrong `BiggestInfluencerId` are never disputed.

### PR DESCRIPTION
**Pull request by Yashk767**
# Description

Added a check for dispute case of biggestInfluence proposed

Fixes #331

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: cmd/dispute.go [hunk 1]
```diff
@@ -27,6 +27,31 @@ func HandleDispute(client *ethclient.Client, config types.Configurations, accoun
...
+			})
+			DisputeBiggestInfluenceProposedTxn, err := utilsStruct.blockManagerUtils.DisputeBiggestInfluenceProposed(client, txnOpts, epoch, uint8(i), biggestInfluenceId)
+			if err != nil {
+				log.Error(err)
+				continue
+			}
+			log.Info("Txn Hash: ", utilsStruct.transactionUtils.Hash(DisputeBiggestInfluenceProposedTxn))
+			utilsStruct.razorUtils.WaitForBlockCompletion(client, utilsStruct.transactionUtils.Hash(DisputeBiggestInfluenceProposedTxn).String())
+		}
+
```
Comment (ashish10677) [inline cmd/dispute.go:54]: @SkandaBhat @hrishikeshio I have a doubt here. If biggestInfluence mismatch is there, and that is disputed for a block, do we need to check for the medians of that block or we can move ahead?

**Review by ashish10677 — APPROVED** [review]
LGTM

**Review by SkandaBhat — APPROVED** [review]
lgtm
