### PR TITLE
Call claimStakerReward only if there reward to claim

### LINKED ISSUE #908: Check reward before calling the `claimStakerReward` function in `claimCommission` command
#### System information

- **OS & Version**: Linux
- **Go version:** go 1.17
- **razor-go version:** v1-mainnet-stable

#### Describe the bug
`claimCommission` command can be called by anyone, and it calls the `claimStakerReward` function of the smart contract without checking if the staker actually has accommodated any commission. 

#### Expected behaviour
The smart contract call must not be made if there is no commission to claim.

#### Actual behaviour
The smart contract call is made regardless of whether the commission is there to claim or not.

#### Backtrace
er

### PR DESCRIPTION
**Pull request by shyam-patel-kira**
fixes #908

### CODE REVIEW

File: cmd/claimCommission.go [hunk 1]
```diff
@@ -38,28 +39,37 @@ func (*UtilsStruct) ClaimCommission(flagSet *pflag.FlagSet) {
...
-	if err != nil {
-		log.Fatal("Error in claiming stake reward: ", err)
+	stakerId, err := razorUtils.GetStakerId(client, address)
+	utils.CheckError("Error in getting stakerId: ", err)
+	callOpts := razorUtils.GetOptions()
+
+	stakerInfo, err := stakeManagerUtils.StakerInfo(client, &callOpts, stakerId)
+	utils.CheckError("Error in getting stakerInfo: ", err)
+
+	if stakerInfo.StakerReward.Cmp(big.NewInt(0)) == 1 {
```
Comment (ashish10677) [inline cmd/claimCommission.go:49]: Instead of `== 1` can you put it as `> 1`. Makes it easier to understand and is consistent with rest of the codebase

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: cmd/claimCommission.go (hunk 1 above)
Comment (shyam-patel-kira) [reply cmd/claimCommission.go:49]: > 1 would not be possible in any case
should I put it as > 0 ?

Comment (shyam-patel-kira) [reply cmd/claimCommission.go]: done

**Review by ashish10677 — APPROVED** [review]

**Review by Yashk767 — APPROVED** [review]
