### PR TITLE
Timeout duration reduced from 120 to 30 secs.

### LINKED ISSUE #363: Timeout while waiting for block completion is too huge.
#### System information

- **OS & Version**: Ubuntu 18.04
- **Go version:** go version go1.17.3 linux/amd64
- **razor-go version:** v0.1.76-patch3

#### Describe the bug
When we wait for block completion, the timeout is 2 times the state length, i.e., 120 seconds.
By the time timeout reaches for state 4 txn, state 0 is almost over and commit failed due to incorrect state.

#### Expected behaviour
Timeout is a smaller value that ends within 15-20 secs.

#### Actual behaviour
Timeout length is 120 secs.

#### Backtrace

````
{"level":"info","msg":"Claiming block reward...","time":"2021-11-23T07:22:58Z"}
{"level":"error","msg":"Error in getting gas limit:  execution reverted: Block can be confirmed by proposer of the block","time":"2021-11-23T07:23:00Z"}
{"level":"debug","msg":"Gas after increment:  0","time":"2021-11-23T07:23:00Z"}
{"level":"debug","msg":"Gas Limit:  20195124","time":"2021-11-23T07:23:00Z"}
{"level":"info","msg":"Txn Hash:  0x9deefb4130c69e6c37ce12de78790c2dc2cf1930385cb26f0acb5130f375cdd1","time":"2021-11-23T07:23:01Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:01Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:05Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:08Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:11Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:15Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:18Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:22Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:25Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:29Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:32Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:36Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:39Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:43Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:47Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:50Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:53Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:23:57Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:00Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:04Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:07Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:11Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:15Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:18Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:22Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:25Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:29Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:32Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:36Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:39Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:43Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:47Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:50Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:54Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:24:58Z"}
{"level":"debug","msg":"Checking if transaction is mined....","time":"2021-11-23T07:25:01Z"}
{"level":"info","msg":"Timeout Passed","time":"2021-11-23T07:25:05Z"}
{"level":"debug","msg":"Block: 21813953  Epoch: 72713  State: Commit  Address: 0x83398CE944282CB832AF7a2f332D7F44FF8DC0c8  Staker ID: 12  Stake: 64296.43  Eth Balance: 4.964514961","time":"2021-11-23T07:25:43Z"}
{"level":"debug","msg":"Data:  [409588 5599474]","time":"2021-11-23T07:25:54Z"}
{"level":"error","msg":"Not commit state","time":"2021-11-23T07:25:54Z"}
````

### PR DESCRIPTION
**Pull request by ashish10677**
Fixes #363

### CODE REVIEW

File: utils/common.go [hunk 1]
```diff
@@ -54,7 +54,7 @@ func checkTransactionReceipt(client *ethclient.Client, _txHash string) int {
 }
 
 func WaitForBlockCompletion(client *ethclient.Client, hashToRead string) int {
-	timeout := core.StateLength * 2
+	timeout := 30
```
Comment (SkandaBhat) [inline utils/common.go:57]: Put this in constants

Comment (ashish10677) [reply utils/common.go]: Done

**Review by SkandaBhat — APPROVED** [review]
