### PR TITLE
Fix : moved gasLimitMultiplier as constant in dispute.go

### LINKED ISSUE #870: dispute.go keep gasLimitMultiplier as a constant and add a comment on why its being used as that

### PR DESCRIPTION
**Pull request by shekhar2807**
# Description

- Moved gasLimitMultiplier as constant in dispute.go

Fixes #870

### CODE REVIEW

File: cmd/dispute.go [hunk 1]
```diff
@@ -266,7 +266,8 @@ func (*UtilsStruct) CheckDisputeForIds(client *ethclient.Client, transactionOpts
 		transactionOpts.Parameters = []interface{}{epoch, blockIndex, missingCollectionId}
 		txnOpts := razorUtils.GetTxnOpts(transactionOpts)
 		gasLimit := txnOpts.GasLimit
-		incrementedGasLimit, err := utilsInterface.IncreaseGasLimitValue(client, gasLimit, 5.5)
+		var gasLimitMultiplier float32 = 5.5 //GasLimitMultiplier is used to increase the gas required from the gasLimit for the following function
```
Comment (ashish10677) [inline cmd/dispute.go:269]: Put this in constants.go

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: core/constants.go [hunk 2]
```diff
@@ -14,6 +14,7 @@ var StateLength = uint64(EpochLength / NumberOfStates)
 var MaxRetries uint = 8
 var NilHash = common.Hash{0x00}
 var BlockCompletionTimeout = 30
+var GasLimitMultiplier float32 = 5.5 //GasLimitMultiplier is used to increase the gas required from the gasLimit for the following function
```
Comment (ashish10677) [inline core/constants.go:17]: Can you rename this to `DisputeGasMultiplier` and put the comment above the variable?

**Review by ashish10677 — CHANGES_REQUESTED** [review]

File: core/constants.go (hunk 2 above)
Comment (shekhar2807) [reply core/constants.go]: Done @ashish10677

**Review by ashish10677 — APPROVED** [review]
